import logging
import uuid
import time
from typing import List, Dict, Optional
from fastapi import FastAPI
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from app.config import settings
from app.services.rag_service import generate_rag_response
from app.services.streaming_service import generate_streaming_rag_response

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)-25s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger(__name__)

# In-memory session store (upgraded to Firestore in production)
SESSION_MEMORY: Dict[str, List[Dict[str, str]]] = {}

app = FastAPI(title=settings.PROJECT_NAME, version=settings.VERSION)

@app.on_event("startup")
async def startup_validation():
    logger.info(f"🚀  {settings.PROJECT_NAME} v{settings.VERSION}")
    if not settings.GROQ_API_KEY:
        logger.critical("🔴  GROQ_API_KEY missing. Offline mode active.")
    else:
        masked = f"{settings.GROQ_API_KEY[:8]}...{settings.GROQ_API_KEY[-4:]}"
        logger.info(f"🟢  GROQ_API_KEY loaded: {masked}")
        logger.info(f"🟢  Model: {settings.GROQ_MODEL_NAME}")
        logger.info(f"🟢  Streaming: ENABLED")
        logger.info(f"🟢  Business Rules: ENABLED")

class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=500)
    session_id: Optional[str] = Field(None, description="Existing session ID for memory continuity")

class ChatResponse(BaseModel):
    reply: str
    intent: str
    session_id: str
    fallback_used: bool
    response_time_ms: int
    retrieved_context: List[dict]

# ── Standard Non-Streaming Endpoint ───────────────────────────────────
@app.post("/api/ai/chat", response_model=ChatResponse)
def ai_chat_endpoint(payload: ChatRequest):
    session_id = payload.session_id or f"cel-{uuid.uuid4().hex[:12]}"
    history = SESSION_MEMORY.get(session_id, [])[-12:]

    logger.info(f"📨  [{session_id}] Query: '{payload.message[:60]}...'")

    response_data = generate_rag_response(
        user_query=payload.message,
        session_id=session_id,
        history=history
    )

    history.append({"role": "user", "content": payload.message})
    history.append({"role": "assistant", "content": response_data["reply"]})
    SESSION_MEMORY[session_id] = history

    if response_data.get("fallback_used"):
        logger.warning(f"⚠️  [{session_id}] OFFLINE FALLBACK")
    else:
        logger.info(f"✅  [{session_id}] Live LLM response in {response_data.get('response_time_ms', 0)}ms")

    return ChatResponse(
        reply=response_data["reply"],
        intent=response_data["intent"],
        session_id=session_id,
        fallback_used=response_data["fallback_used"],
        response_time_ms=response_data.get("response_time_ms", 0),
        retrieved_context=response_data["retrieved_context"]
    )

# ── Streaming SSE Endpoint (Supervisor Requirement) ───────────────────
@app.post("/api/ai/chat/stream")
async def ai_chat_stream_endpoint(payload: ChatRequest):
    """
    Real-time streaming endpoint using Server-Sent Events (SSE).
    Yields tokens as they are generated by the Groq LLM.
    """
    session_id = payload.session_id or f"cel-{uuid.uuid4().hex[:12]}"
    history = SESSION_MEMORY.get(session_id, [])[-12:]
    
    logger.info(f"📨  [STREAM] [{session_id}] Query: '{payload.message[:60]}...'")
    start_time = time.time()

    async def event_generator():
        full_response = []
        async for token in generate_streaming_rag_response(
            payload.message, session_id, history
        ):
            full_response.append(token)
            yield f"data: {token}\n\n"
        
        # Persist after stream completes
        complete_reply = "".join(full_response)
        history.append({"role": "user", "content": payload.message})
        history.append({"role": "assistant", "content": complete_reply})
        SESSION_MEMORY[session_id] = history
        
        elapsed_ms = int((time.time() - start_time) * 1000)
        logger.info(f"✅  [STREAM] [{session_id}] Completed in {elapsed_ms}ms")
        
        yield f"data: [DONE]\n\n"

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "X-Session-Id": session_id,
            "Cache-Control": "no-cache",
            "Connection": "keep-alive"
        }
    )